title: 'Dr. Sun, Yunfang''s Blog'
email: yfsun@protonmail.com
description: >-
Dr. Sun's research focuses on coastal hazard modeling, storm surge and flood dynamics, and high-resolution numerical simulations of coupled ocean–atmosphere systems. He works on quantifying extreme event risk, developing physics-based inundation models, and creating hazard and exposure metrics used in climate risk analysis and resilience planning. His work integrates physical modeling, data-driven methods, and machine learning to improve coastal flood prediction and risk assessment.
baseurl: ''
url: ''
linkedin_username: yfsun
#youtube_username: aaaa
#google_scholar_username: i6pxa-UAAAAJ

#social-network-links:
#ORCID: 0000-0001-6656-2581
#google-scholar: i6pxa-UAAAAJ

theme: minima




paginate: 5
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
