title: 'Dr. Sun, Yunfang''s Blog'
email: yfsun@protonmail.com
description: >-
  Dr. Sun's research interests include climate change, sea level rise, data
  mining & machine learning, harmful algal blooms, fishery dynamics, estuary and
  coastal ocean processes, remote sensing & HF radar ocean observation, dynamics
  of coupled oceanic-atmospheric modeling.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
